title: Koras02 Math Blog
description: Koras02 Math Blog
baseurl: ""
url: "https://koras02.github.io/"

theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    preview: none
include:
  - _pages
livereload: true
sass:
  style: compressed
